channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.10.14 #original version is 3.7.5
  - pip
  - pip:
      - azureml-mlflow==1.38.0
      - azure-ai-ml==1.0.0
      - pyarrow==10.0.0
      - scikit-learn==1.5.2 #original version is 0.24.1
      - pandas==2.2.3 # orginal version 1.2.1
      - joblib==1.4.2 #original version 1.0.0
      - matplotlib==3.10.1 # original version 3.3.3
      - git+https://github.com/microsoft/AzureML-Observability#subdirectory=aml-obs-client
      - git+https://github.com/microsoft/AzureML-Observability#subdirectory=aml-obs-collector
